<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Montserrat');
        body {
            font-family: 'Montserrat', sans-serif;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row">
            <p>
                <a href="/todos">Todos</a>
                <a href="/logout">LogOut</a>
            </p>
        </div>
    </div>
    </div>
</body>
<script>

</script>

</html>