<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Montserrat');
        body {
            font-family: 'Montserrat', sans-serif;
        }

        button {
            padding: 5px 5px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            background-color: white;
            color: #a3a3a3;
            border: 2px solid #a3a3a3;
            -webkit-transition-duration: 0.4s;
            transition-duration: 0.4s;
        }

        button:hover {
            background-color: #a3a3a3;
            color: white;
        }
    </style>
</head>

<body>
    <div class="container" style="text-align: center">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">Login</div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post" action="/login">

                        <div class="form-group">
                            <label for="username">Username</label>
                            <input id="username" type="text" class="form-control" name="username" value="" required autofocus>
                        </div>

                        <div class="form-group">
                            <label for="password">Password</label>
                            <input id="password" type="password" class="form-control" name="password" required>
                        </div>

                        <div class="form-group">
                            <button type="submit">
                                Login
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</body>
<script>

</script>

</html>